# SPDX-FileCopyrightText: 2026 TinyPhi
# SPDX-License-Identifier: AGPL-3.0-only
"""Asset error classes (§C1.5.1, §C4.5, M2.1-T2, M2.1-T3)."""

from __future__ import annotations

from typing import ClassVar

from app.core.problems import ConflictError, FieldError, ValidationFailedError

__all__ = ["CustomFieldValidationError", "TagConflictError", "TagInvalidError"]


class CustomFieldValidationError(ValidationFailedError):
    """One or more custom field values fail their definition's type or rules (§B8.1, §B10)."""

    status_code = 422
    code: ClassVar[str] = "asset.custom_field_invalid"
    title: ClassVar[str] = "Custom field validation failed"
    default_detail: ClassVar[str] = "One or more custom field values are invalid. See errors for each field."
    description: ClassVar[str] = (
        "A custom field value did not match its definition's type or rules (required, min, max, "
        "regex, options, size), named an unknown field key, or violated the unique-in-organization "
        "rule. `errors` lists each field as `custom_fields.<key>`."
    )

    def __init__(self, errors: list[FieldError]) -> None:
        super().__init__(errors=errors)


class TagInvalidError(ValidationFailedError):
    """A supplied asset tag does not match the organization's tag format (M2.1-T3, §B7.3)."""

    status_code = 422
    code: ClassVar[str] = "asset.tag_invalid"
    title: ClassVar[str] = "Asset tag invalid"
    default_detail: ClassVar[str] = "The supplied tag does not match this organization's tag format."
    description: ClassVar[str] = (
        "A tag supplied with a create or import (rather than generated) did not match the "
        "organization's domain-template tag format or category tag-prefix override: wrong prefix, "
        "wrong separator, or a numeric part shorter than the configured digit count."
    )

    def __init__(self, detail: str | None = None) -> None:
        super().__init__(detail)


class TagConflictError(ConflictError):
    """A supplied asset tag is already used by another asset in the same organization (M2.1-T3)."""

    status_code = 409
    code: ClassVar[str] = "asset.tag_conflict"
    title: ClassVar[str] = "Asset tag already in use"
    default_detail: ClassVar[str] = "This tag is already used by another asset in this organization."
    description: ClassVar[str] = (
        "A supplied tag (from a reserved QR tag or an import row) is already used by another "
        "asset in the same organization. Tags generated by the organization's own sequence never "
        "collide; this only happens for a tag the caller supplies."
    )

    def __init__(self, detail: str | None = None) -> None:
        super().__init__(detail)
