#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 TinyPhi
# SPDX-License-Identifier: AGPL-3.0-only
"""Generate docs/reference/events.md from the event registries (master plan §C7.2 "New event type").

Two sources, both in the backend: the automation event registry (events a rule can react to, with
their payload fields, holder and personal fields) and the notification module's own published
events. The page is generated, so it cannot drift from the code.

Usage (from the repository root or backend/):
    uv run --project backend python scripts/gen-events-reference.py           write the file
    uv run --project backend python scripts/gen-events-reference.py --check   exit 1 if the file is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BACKEND_DIR = REPO_ROOT / "backend"
OUTPUT = REPO_ROOT / "docs" / "reference" / "events.md"

if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

from app.engines.automation.registry import default_registry
from app.modules.notifications.events import NOTIFICATION_EVENTS

HEADER = """<!--
SPDX-FileCopyrightText: 2026 TinyPhi
SPDX-License-Identifier: AGPL-3.0-only
-->

<!-- Generated by scripts/gen-events-reference.py from backend/app/engines/automation/registry.py and backend/app/modules/notifications/events.py. Do not edit by hand. -->

# Events

Every state change writes an audit event and an outbox row in one transaction (§B9.3). The outbox
row's `payload` is the flat JSON object listed here. The worker dispatches each event to its
subscribers, which is how a notification is produced.

## Events an automation rule can react to

A rule's `when` names one of these; its `if` conditions and recipient references may use only the
fields listed. `holder` names the field that identifies the member the notice is about, when the
event has one. Fields marked personal are left out of an outbound payload unless the installation
allows personal data.

| Event | Fields | Holder | Personal fields |
| --- | --- | --- | --- |
"""

NOTIFICATION_HEADER = """
## Events published by the notification module

Not available to automation rules. Secret values are never in a payload.

| Event | Aggregate | Fields | Meaning |
| --- | --- | --- | --- |
"""


def _codes(items: list[str] | tuple[str, ...] | frozenset[str]) -> str:
    return ", ".join(f"`{item}`" for item in sorted(items)) if items else "none"


def render() -> str:
    """The whole page."""
    registry = default_registry()
    rows = []
    for event_type in sorted(registry.known_event_types()):
        spec = registry.get(event_type)
        assert spec is not None
        holder = f"`{spec.holder_field}`" if spec.holder_field else "none"
        rows.append(f"| `{event_type}` | {_codes(spec.fields)} | {holder} | {_codes(spec.personal_fields)} |")
    notification_rows = [
        f"| `{event_type}` | `{event.aggregate_type}` | {_codes(event.fields)} | {event.description} |"
        for event_type, event in sorted(NOTIFICATION_EVENTS.items())
    ]
    return HEADER + "\n".join(rows) + "\n" + NOTIFICATION_HEADER + "\n".join(notification_rows) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else None)
    parser.add_argument("--check", action="store_true", help="exit 1 when the file is not current")
    args = parser.parse_args(argv)
    content = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8").replace("\r\n", "\n") != content:
            sys.stderr.write(f"{OUTPUT.relative_to(REPO_ROOT)} is stale; run scripts/gen-events-reference.py\n")
            return 1
        return 0
    OUTPUT.write_text(content, encoding="utf-8", newline="\n")
    sys.stdout.write(f"wrote {OUTPUT.relative_to(REPO_ROOT)}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
